# SPDX-FileCopyrightText: Heiko Schaefer <heiko@schaefer.name>
# SPDX-License-Identifier: CC0-1.0

[workspace]
resolver = "2"
members = [
    "rpgpie-sop",
    "rpgpie-sop-oct",
    "rsop",
    "rsop-oct",
]
default-members = ["rsop"]

[profile.release]
codegen-units = 1
